apiVersion: v1
kind: ServiceAccount
metadata:
  name: restricted-service-account
  namespace: default
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minimal-access
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restricted-access-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: restricted-service-account
  namespace: default
roleRef:
  kind: Role
  name: minimal-access
  apiGroup: rbac.authorization.k8s.io
