site_name: Kubernetes
site_description: One place for everything about Kubernetes
site_url: https://maharshi-mimo.github.io/Kubernetes-All-in-One/
repo_url: https://github.com/Maharshi-Mimo/Kubernetes-All-in-One
repo_name: Maharshi-Mimo/Kubernetes-All-in-One

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Introduction:
    - Certification: 01 - Introduction/01 - Certification.md
  - Core Concepts:
    - Cluster Architecture: 02 - Core Concepts/01 - Cluster Architecture.md
    - Kube API Server: 02 - Core Concepts/02-Kube-API-Server.md
    - Kubernetes Control Plane: 02 - Core Concepts/03-Kubernetes-Controlplane.md
    - ETCD Server: 02 - Core Concepts/04-ETCD-server.md
    - Kube Scheduler: 02 - Core Concepts/05-Kube-Scheduler.md
    - Kube Services: 02 - Core Concepts/06-kube-Services.md
    - Kubelet: 02 - Core Concepts/07-Kubelet.md
    - Kube Proxy: 02 - Core Concepts/08-Kube-Proxy.md
    - Container Runtime Interface: 02 - Core Concepts/09-Container-Runtime-Interface.md
    - Namespace: 02 - Core Concepts/10-Namespace.md
    - KubeConfig: 02 - Core Concepts/11-KubeConfig.md
    - Cloud Controller Manager: 02 - Core Concepts/12-Cloud-Controller-Manager.md
    - Nodes: 02 - Core Concepts/13-Nodes.md
    - Kube Controller Manager: 02 - Core Concepts/14-Kube-Controller-Manager.md
  - Resources:
    - Pod: 03 - Resources/01-Pod.md
    - ReplicaSet: 03 - Resources/02-ReplicaSet.md
    - Deployments: 03 - Resources/03-Deployments.md
    - StatefulSet: 03 - Resources/04-StatefulSet.md
    - DaemonSet: 03 - Resources/05-DaemonSet.md
    - LimitRange & ResourceQuota: 03 - Resources/06-LimitRange_&_ResourceQuota.md
    - CronJobs: 03 - Resources/07-CronJobs.md
    - ConfigMap: 03 - Resources/08-ConfigMap.md
    - HPA: 03 - Resources/09-HPA.md
    - Namespace: 03 - Resources/10-Namespace.md
  - Network & Services:
    - CNI: 04 - Network & Services/01-CNI.md
    - CoreDNS: 04 - Network & Services/02-CoreDNS.md
    - ClusterIP: 04 - Network & Services/03-ClusterIP.md
    - LoadBalancer: 04 - Network & Services/04-LoadBalancer.md
    - Ingress: 04 - Network & Services/05-Ingress.md
    - NodePort: 04 - Network & Services/06-NodePort.md
    - ExternalName: 04 - Network & Services/07-ExternalName.md
    - NetworkPolicies: 04 - Network & Services/08-NetworkPolicies.md
    - EndpointSlices: 04 - Network & Services/09-EndpointSlices.md
  - Storage:
    - CSI: 05 - Storage/01-CSI.md
    - Volumes: 05 - Storage/02-Volumes.md
    - PersistentVolume: 05 - Storage/03-PersistentVolume.md
    - PersistentVolumeClaim: 05 - Storage/04-PersistentVolumeClaim.md
    - StorageClass: 05 - Storage/05-StorageClass.md
    - VolumeExpansion: 05 - Storage/06-VolumeExpansion.md
    - VolumeCloning: 05 - Storage/07-VolumeCloning.md
    - VolumeSnapshots: 05 - Storage/08-VolumeSnapshots.md
    - CrossPlatformStorage: 05 - Storage/09-CrossPlatformStorage.md
    - StorageCapacity: 05 - Storage/10-StorageCapacity.md
    - Ephemeral Storage: 05 - Storage/11-Ephemral_Storage.md
  - Security:
    - Kubernetes Security: 06 - Security/01-kubernetes-security.md
    - Authentication: 06 - Security/02-Authentication.md
    - Authorization: 06 - Security/03-Authorization.md
    - SSL Cert: 06 - Security/04-SSL Cert.md
    - Disaster Recovery: 06 - Security/05-Disaster Recovery.md
    - Infrastructure Security: 06 - Security/06-Infrastructure Security.md
    - Secret Management: 06 - Security/07-Secret Management.md
    - Security Proxy: 06 - Security/08-Security Proxy.md
    - Admission Controller: 06 - Security/09-Admission_Controller.md
    - Compliance and Audit: 06 - Security/10-Compliance_and_Audit.md
    - Supply Chain Security: 06 - Security/11-Supply-Chain-Security.md
