apiVersion: v1
kind: Config
preferences: {}

# Cluster definitions
clusters:
- name: development-cluster
  cluster:
    server: https://dev.example.com:6443
    certificate-authority-data: <base64-encoded-ca-cert>
- name: production-cluster
  cluster:
    server: https://prod.example.com:6443
    certificate-authority-data: <base64-encoded-ca-cert>

# User definitions
users:
- name: dev-user
  user:
    client-certificate-data: <base64-encoded-cert>
    client-key-data: <base64-encoded-key>
- name: prod-user
  user:
    token: <bearer-token>

# Context definitions
contexts:
- name: dev-context
  context:
    cluster: development-cluster
    namespace: development
    user: dev-user
- name: prod-context
  context:
    cluster: production-cluster
    namespace: production
    user: prod-user

# Set the current active context
current-context: dev-context
